project:
  type: website
  output-dir: docs

lang: en

website:
  title: "Dream of the Red Chamber Dataviz"

format:
  html:
    theme: cosmo
    css: annexes/styles.css
    toc: true


editor: visual

